language: python
python:
  - "2.7"
before_script:
    - mysql -e 'create database pyramid_sqlalchemy_utility;'
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: "pip install -r requirements-test.txt && pip install -e ."
# command to run tests, e.g. python setup.py test
script:  "python setup.py nosetests"
